# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v2
      
    - name: Installing required packages
      run: sudo apt install git curl
    - name: Installing Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Adding Rust to ENV
      run: source $HOME/.cargo/env
    - name: Installing Cobalt
      run: curl -LSfs https://japaric.github.io/trust/install.sh |
        sh -s --
        --git cobalt-org/cobalt.rs
        --crate cobalt
        --force
        --target x86_64-unknown-linux-gnu
        --tag v0.15.0
    - name: Build Cobalt Site
      run: cobalt build -c ./src/_cobalt.yml -d ./build
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvvvO"
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
